services:
  capstone-prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  capstone-mysql:
    image: capstone-mysql
    ports:
      - "3306:3306"
    depends_on:
      - capstone-prometheus
  capstone-ingress-api:
    image: capstone-ingress-api
    ports:
      - "8000:8000"
    depends_on:
      - capstone-prometheus
      - capstone-mysql
  capstone-etl:
    image: capstone-etl
    depends_on:
      - capstone-ingress-api
  capstone-grafana:
    image: grafana/grafana
    depends_on:
      - capstone-prometheus
      - capstone-mysql
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
